const { GoogleGenAI } = require('@google/genai');
const Dashboard = require('../models/Dashboard');
const Widget = require('../models/Widget');

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

class AIDashboardService {

  // Generate a full dashboard layout from a user prompt
  async generateDashboardFromPrompt(prompt) {
    const count = await Dashboard.countDocuments({ isAutoGenerated: true });
    const dashboard = await Dashboard.create({
      name: `AI Analysis ${count + 1}`,
      isAutoGenerated: true,
      widgets: [],
      layouts: { lg: [], md: [], sm: [] }
    });

    const schema = `
Widget types: "bar", "line", "pie", "kpi", "table"
xAxisField options: "product", "status", "orderDate", "customer.name", "customer.city"
yAxisField options: "totalAmount", "quantity"
aggregation options: "sum", "average", "count"
`;

    try {
      const result = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: `You are a dashboard builder. Based on this objective: "${prompt}", generate a JSON array of 4-6 dashboard widgets. Each widget must have: title (string), type (${schema}), config: { xAxisField, yAxisField, aggregation }. Return ONLY a valid JSON array. No markdown, no explanation.`
      });

      const rawText = result.text || result?.candidates?.[0]?.content?.parts?.[0]?.text || '';
      if (!rawText) throw new Error('AI returned an empty response.');

      const cleaned = rawText.replace(/```json\n?/gi, '').replace(/```\n?/gi, '').trim();
      let widgetsData;
      try {
        widgetsData = JSON.parse(cleaned);
      } catch (parseErr) {
        throw new Error('Failed to parse AI response into JSON. ' + parseErr.message);
      }

      if (!Array.isArray(widgetsData) || widgetsData.length === 0) {
        throw new Error('AI returned an invalid widget array.');
      }

      const savedWidgets = await Widget.insertMany(widgetsData);
      const widgetIds = savedWidgets.map(w => w._id.toString());

      const cols = 12;
      const defaultW = 4;
      const defaultH = 4;
      const lgLayouts = savedWidgets.map((w, i) => ({
        i: w._id.toString(),
        x: (i * defaultW) % cols,
        y: Math.floor((i * defaultW) / cols) * defaultH,
        w: w.type === 'kpi' ? 3 : defaultW,
        h: w.type === 'kpi' ? 2 : defaultH,
        minW: 2, minH: 2
      }));

      dashboard.widgets = widgetIds;
      dashboard.layouts = { lg: lgLayouts, md: lgLayouts, sm: lgLayouts };
      await dashboard.save();

      return await Dashboard.findById(dashboard._id).populate('widgets');
    } catch (err) {
      console.error('AI Generation Failed:', err);
      throw new Error('Failed to parse AI response. ' + err.message);
    }
  }

  // Analyze a user requirement and respond with actionable insight
  async analyzeRequirement(prompt, history = []) {
    const contents = [
      ...history.map(h => ({
        role: h.role,
        parts: [{ text: h.text }]
      })),
      {
        role: 'user',
        parts: [{
          text: `You are Workspan Analytics AI — a friendly, expert BI assistant for the Halleyx Dashboard. The user asked: "${prompt}". Respond concisely with actionable dashboard insights. If they want to build a dashboard, suggest widget types (bar, line, pie, kpi, table) and what data fields to use. Keep responses under 180 words.`
        }]
      }
    ];

    const result = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents
    });

    const text = result.text || result?.candidates?.[0]?.content?.parts?.[0]?.text || 'I couldn\'t generate a response. Please try again.';
    return { text, role: 'model' };
  }
}

module.exports = new AIDashboardService();
