const { GoogleGenerativeAI } = require('@google/generative-ai');
const Dashboard = require('../models/Dashboard');
const Widget = require('../models/Widget');

// Use the standard Official Gemini SDK
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

class AIDashboardService {
  constructor() {
    // Using gemini-1.5-flash for better stability and free-tier compatibility
    this.modelName = 'gemini-1.5-flash';
  }

  // Generate a full dashboard layout from a user prompt
  async generateDashboardFromPrompt(prompt) {
    const dashboard = await Dashboard.create({
      name: `AI Draft: ${prompt.substring(0, 20)}...`,
      isAutoGenerated: true,
      widgets: [],
      layouts: { lg: [], md: [], sm: [] }
    });

    const schemaInfo = `
Widget types: "bar", "line", "pie", "kpi", "table"
xAxisField options: "product", "status", "orderDate", "customer.name", "customer.city"
yAxisField options: "totalAmount", "quantity"
aggregation options: "sum", "average", "count"
`;

    try {
      const model = genAI.getGenerativeModel({ 
        model: this.modelName,
        generationConfig: { responseMimeType: "application/json" }
      });

      const result = await model.generateContent(
        `You are a dashboard architect. Generate a JSON array of 4-6 widgets for: "${prompt}". 
        ${schemaInfo}
        Return ONLY valid JSON array. Structure: [{ "title": string, "type": string, "config": { "xAxisField": string, "yAxisField": string, "aggregation": string }}]`
      );

      const response = await result.response;
      let widgetsData;
      
      try {
        widgetsData = JSON.parse(response.text());
      } catch (parseErr) {
        console.error('AI Response Parse Error:', response.text());
        throw new Error('AI produced invalid JSON.');
      }

      if (!Array.isArray(widgetsData)) throw new Error('AI response is not an array.');

      const savedWidgets = await Widget.insertMany(widgetsData);
      const widgetIds = savedWidgets.map(w => w._id);

      const lgLayouts = savedWidgets.map((w, i) => ({
        i: w._id.toString(),
        x: (i * 4) % 12,
        y: Math.floor((i * 4) / 12) * 4,
        w: w.type === 'kpi' ? 3 : 4,
        h: w.type === 'kpi' ? 2 : 4,
      }));

      dashboard.widgets = widgetIds;
      dashboard.layouts = { lg: lgLayouts, md: lgLayouts, sm: lgLayouts };
      await dashboard.save();

      return await Dashboard.findById(dashboard._id).populate('widgets');
    } catch (err) {
      this.handleAiError(err);
    }
  }

  // Analyze a user requirement and respond with actionable insight
  async analyzeRequirement(prompt, history = []) {
    try {
      const model = genAI.getGenerativeModel({ model: this.modelName });
      
      const chat = model.startChat({
        history: history.map(h => ({
          role: h.role === 'model' ? 'model' : 'user',
          parts: [{ text: h.text }],
        })),
        generationConfig: {
          maxOutputTokens: 250,
        },
      });

      const instruction = `Context: Halleyx Dashboard Assistant. User: "${prompt}". Instructions: Concise analysis, suggestions for widgets (bar/line/pie/kpi), use data fields like totalAmount/product/status. Max 150 words.`;
      
      const result = await chat.sendMessage(instruction);
      const response = await result.response;
      return { text: response.text(), role: 'model' };
    } catch (err) {
      this.handleAiError(err);
    }
  }

  handleAiError(err) {
    console.error('Gemini AI Service Error:', err);
    
    // Check for Rate Limit (429)
    if (err.status === 429 || (err.message && err.message.includes('429'))) {
      const error = new Error('AI Quota Exceeded. The free tier of Gemini has strict limits. Please wait 60 seconds and try again.');
      error.statusCode = 429;
      throw error;
    }

    // Check for Invalid Key
    if (err.status === 403 || err.status === 401) {
      throw new Error('AI Authentication Failed. Please verify your Gemini API key in Settings.');
    }

    throw new Error('AI Service encountered an unexpected error: ' + err.message);
  }
}

module.exports = new AIDashboardService();
