const { GoogleGenAI } = require('@google/genai');
const Dashboard = require('../models/Dashboard');
const Widget = require('../models/Widget');

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

class AIDashboardService {
  static async generateDashboardFromPrompt(prompt) {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not set in environments.");
    }

    // 1. Create the new dashboard with a timestamp or count to keep it unique
    const count = await Dashboard.countDocuments({ isAutoGenerated: true });
    const dashboard = await Dashboard.create({ 
      name: `AI Analysis ${count + 1}`, 
      isAutoGenerated: true,
      layouts: { lg: [], md: [], sm: [], xs: [], xxs: [] }
    });

    // We define the schema limits so the AI answers perfectly
    const promptInstructions = `
      You are an analytics dashboard configuration generator.
      The user will request a dashboard layout: "${prompt}"

      You MUST respond with a RAW JSON array ONLY, without markdown wrapping (like \`\`\`json).
      Each object in the array represents a widget.
      
      Allowed widget properties:
      - title (String)
      - type (Enum: "kpi", "bar", "line", "pie", "table")
      - xAxisField (String: "product", "status", "orderDate", "customer.city")
      - yAxisField (String: "totalAmount", "quantity")
      - aggregation (Enum: "sum", "average", "count", "none")
      - w (Number: Width on a 12-column grid, 1-12)
      - h (Number: Height in grid rows, 3-8)
      - x (Number: X position 0-11)
      - y (Number: Y position 0-100)

      Example Output:
      [
        {"title": "Total Revenue", "type": "kpi", "yAxisField": "totalAmount", "aggregation": "sum", "w": 4, "h": 2, "x": 0, "y": 0},
        {"title": "Sales by Product", "type": "bar", "xAxisField": "product", "yAxisField": "totalAmount", "aggregation": "sum", "w": 8, "h": 4, "x": 0, "y": 2}
      ]
    `;

    try {
        const result = await ai.models.generateContent({
            model: 'models/gemini-flash-latest',
            contents: promptInstructions
        });
        
        // The @google/genai SDK returns text at candidates[0].content.parts[0].text
        let text = "";
        if (result.candidates && result.candidates[0] && result.candidates[0].content && result.candidates[0].content.parts && result.candidates[0].content.parts.length > 0) {
            text = result.candidates[0].content.parts
                .filter(p => p.text)
                .map(p => p.text)
                .join('');
        }
        
        if (!text) {
            console.error("AI Full Response:", JSON.stringify(result, null, 2));
            throw new Error("AI returned an empty response or unexpected structure.");
        }

        console.log("Extracted Text:", text.substring(0, 200));

        // Clean markdown backticks if AI accidentally included them
        if (text.includes('\`\`\`')) {
            text = text.replace(/\`\`\`json/g, '').replace(/\`\`\`/g, '').trim();
        }

        let generatedConfig;
        try {
            generatedConfig = JSON.parse(text);
        } catch (parseErr) {
            console.error("JSON Parse Error. Content was:", text);
            throw new Error("Failed to parse AI response into JSON. " + parseErr.message);
        }

        const widgetsData = generatedConfig.map(conf => ({
            dashboardId: dashboard._id,
            title: conf.title,
            type: conf.type,
            config: { 
              xAxisField: conf.xAxisField, 
              yAxisField: conf.yAxisField, 
              aggregation: conf.aggregation,
              chartConfig: { showLegend: true }
            },
            _tempLayout: { x: conf.x || 0, y: conf.y || 0, w: conf.w || 4, h: conf.h || 4 }
        }));

        // 3. Save widgets to DB
        const savedWidgets = await Widget.insertMany(widgetsData);

        // 4. Update Dashboard layout and widget references
        dashboard.widgets = savedWidgets.map(w => w._id);
        
        savedWidgets.forEach((widget, idx) => {
          const match = widgetsData[idx];
          if (match && match._tempLayout) {
            const layoutItem = {
              i: widget._id.toString(),
              x: match._tempLayout.x,
              y: match._tempLayout.y,
              w: match._tempLayout.w,
              h: match._tempLayout.h
            };
            dashboard.layouts.lg.push(layoutItem);
            dashboard.layouts.md.push(layoutItem);
            dashboard.layouts.sm.push(layoutItem);
            dashboard.layouts.xs.push(layoutItem);
            dashboard.layouts.xxs.push(layoutItem);
          }
        });

        await dashboard.save();
        return await Dashboard.findById(dashboard._id).populate('widgets');

    } catch (err) {
        console.error("AI Generation Failed:", err);
        throw new Error("Failed to parse AI response. " + err.message);
    }
  }

  static async analyzeRequirement(prompt, history = []) {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not set in environments.");
    }

    const analysisPrompt = `
      You are an AI requirements analyst for a business intelligence dashboard.
      The user wants to create a dashboard based on this request: "${prompt}"
      
      Previous conversation history:
      ${JSON.stringify(history)}

      Analyze the request and provide a JSON response with these fields:
      - summary: A 1-sentence summary of what you understand they want.
      - questions: An array of 2 short, specific questions to clarify their needs (e.g., specific products, timeframes, or KPIs).
      - isReady: Boolean. Set to true ONLY if the prompt is specific enough to generate at least 3 relevant widgets.
      - suggestedWidgets: An array of 3-4 widget titles and types you plan to include.
      
      Example response:
      {
        "summary": "You want to track sales performance and product trends.",
        "questions": ["Should we focus on a specific region?", "Do you want to see monthly or weekly trends?"],
        "isReady": false,
        "suggestedWidgets": [
          {"title": "Total Revenue", "type": "kpi"},
          {"title": "Sales by Product", "type": "bar"}
        ]
      }

      Respond with RAW JSON ONLY. No markdown formatting.
    `;

    try {
      const result = await ai.models.generateContent({
        model: 'models/gemini-flash-latest',
        contents: analysisPrompt
      });

      let text = "";
      if (result.candidates && result.candidates[0] && result.candidates[0].content && result.candidates[0].content.parts) {
        text = result.candidates[0].content.parts.map(p => p.text).join('');
      }

      if (text.includes('\`\`\`')) {
        text = text.replace(/\`\`\`json/g, '').replace(/\`\`\`/g, '').trim();
      }

      return JSON.parse(text);
    } catch (err) {
      console.error("AI Analysis Failed:", err);
      throw new Error("Failed to analyze requirements: " + err.message);
    }
  }
}

module.exports = AIDashboardService;
