const Dashboard = require('../models/Dashboard');
const Widget = require('../models/Widget');
const Order = require('../models/Order');

class AutoGeneratorService {
  static async generateDashboard() {
    // 1. Delete previous auto-generated dashboard to keep it single
    const existingDash = await Dashboard.findOne({ isAutoGenerated: true });
    if (existingDash) {
      await Widget.deleteMany({ dashboardId: existingDash._id });
      await existingDash.deleteOne();
    }

    // 2. Create the new dashboard
    const dashboard = await Dashboard.create({ 
      name: 'Workspan AI Analytics', 
      isAutoGenerated: true,
      layouts: { lg: [], md: [], sm: [] }
    });

    const widgetsData = [];
    let currentY = 0; // Row tracker for grid

    // Rule 1: Numeric Fields -> Total Revenue KPI + Total Orders KPI
    widgetsData.push(this.createWidgetDef(dashboard._id, 'kpi', 'Total Revenue', 'totalAmount', 'sum', 0, currentY, 3, 3));
    widgetsData.push(this.createWidgetDef(dashboard._id, 'kpi', 'Total Orders', 'quantity', 'count', 3, currentY, 3, 3));
    widgetsData.push(this.createWidgetDef(dashboard._id, 'kpi', 'Average Order Value', 'totalAmount', 'average', 6, currentY, 3, 3));
    
    currentY += 3; // Move to next row

    // Rule 2: Categorical + Numeric -> Revenue by Product (Bar Chart)
    widgetsData.push(this.createWidgetDef(dashboard._id, 'bar', 'Revenue by Product', 'totalAmount', 'sum', 0, currentY, 8, 6, 'product'));
    
    // Rule 4: Status Distribution -> Order Status (Pie Chart)
    widgetsData.push(this.createWidgetDef(dashboard._id, 'pie', 'Order Status Distribution', 'quantity', 'count', 8, currentY, 4, 6, 'status'));
    
    currentY += 6; // Move to next row

    // Rule 3: Time Series -> Orders Over Time (Line Chart)
    widgetsData.push(this.createWidgetDef(dashboard._id, 'line', 'Orders Over Time', 'totalAmount', 'sum', 0, currentY, 8, 6, 'orderDate'));

    // Additional Distribution
    widgetsData.push(this.createWidgetDef(dashboard._id, 'bar', 'Sales by City', 'totalAmount', 'sum', 8, currentY, 4, 6, 'customer.city'));

    currentY += 6;

    // Rule 5: Always include Table -> Data Grid
    widgetsData.push(this.createWidgetDef(dashboard._id, 'table', 'Recent Customer Orders', null, 'none', 0, currentY, 12, 8));

    // 3. Save widgets to DB
    const savedWidgets = await Widget.insertMany(widgetsData);

    // 4. Update Dashboard layout and widget references
    dashboard.widgets = savedWidgets.map(w => w._id);
    
    // Construct lg layout based on our initial rules (responsive sets can be derived)
    savedWidgets.forEach(widget => {
      // Find the widget config that we generated
      const match = widgetsData.find(wd => wd.title === widget.title);
      if (match && match._tempLayout) {
        const layoutItem = {
          i: widget._id.toString(),
          x: match._tempLayout.x,
          y: match._tempLayout.y,
          w: match._tempLayout.w,
          h: match._tempLayout.h
        };
        dashboard.layouts.lg.push(layoutItem);
        dashboard.layouts.md.push(layoutItem);
        dashboard.layouts.sm.push(layoutItem);
        dashboard.layouts.xs.push(layoutItem);
        dashboard.layouts.xxs.push(layoutItem);
      }
    });

    await dashboard.save();
    return await Dashboard.findById(dashboard._id).populate('widgets');
  }

  static createWidgetDef(dashboardId, type, title, yField, agg, x, y, w, h, xField = null) {
    return {
      dashboardId,
      title,
      type,
      config: { 
        xAxisField: xField, 
        yAxisField: yField, 
        aggregation: agg,
        chartConfig: {
          showLegend: true
        }
      },
      // We store layout temporarily to construct the grid afterwards when we get the object ID
      _tempLayout: { x, y, w, h }
    };
  }
}

module.exports = AutoGeneratorService;
