const AutoGeneratorService = require('../services/AutoGeneratorService');
const Order = require('../models/Order');
const Widget = require('../models/Widget');
const mongoose = require('mongoose');
const AIDashboardService = require('../services/AIDashboardService');

// @desc    Auto Generate Dashboard
// @route   POST /api/analytics/auto-generate
// @access  Public
exports.autoGenerateDashboard = async (req, res) => {
  try {
    const generatedDashboard = await AutoGeneratorService.generateDashboard();
    res.status(201).json(generatedDashboard);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Error generating dashboard', error: error.message });
  }
};

// @desc    AI Generate Dashboard based on Prompt
// @route   POST /api/analytics/ai-generate
// @access  Private
exports.aiGenerateDashboard = async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt) return res.status(400).json({ message: 'Prompt is required' });
    
    const dashboard = await AIDashboardService.generateDashboardFromPrompt(prompt);
    res.status(201).json(dashboard);
  } catch (error) {
    const status = error.statusCode || 500;
    res.status(status).json({ message: error.message });
  }
};

// @desc    AI Analyze Requirement / Chat
// @route   POST /api/analytics/ai-analyze
// @access  Private
exports.aiAnalyzeRequirement = async (req, res) => {
  try {
    const { prompt, history } = req.body;
    const response = await AIDashboardService.analyzeRequirement(prompt, history);
    res.json(response);
  } catch (error) {
    const status = error.statusCode || 500;
    res.status(status).json({ message: error.message });
  }
};


// @desc    Fetch Aggregated Data for a Widget dynamically based on date range
// @route   POST /api/analytics/data
// @access  Public
exports.getWidgetData = async (req, res) => {
  try {
    const { widgetId, dateRange } = req.body;
    
    // 1. Fetch Widget Config or use mock if temporary ID
    // 1. Fetch Widget Config or use provided config for preview
    let widget;
    if (mongoose.Types.ObjectId.isValid(widgetId)) {
        widget = await Widget.findById(widgetId);
    }
    
    // If config is provided in body (preview/edit mode), override the stored config
    if (req.body.config) {
        if (widget) {
            widget.config = { ...widget.config, ...req.body.config };
        } else {
            widget = {
                type: req.body.type || 'bar',
                config: req.body.config
            };
        }
    }

    // Default Fallback for missing widget/config
    if (!widget) {
        widget = {
            type: 'bar',
            config: { xAxisField: 'product', yAxisField: 'totalAmount', aggregation: 'sum' }
        };
    }

    // 2. Build Date Match Stage for MongoDB Aggregation
    const matchStage = {};
    if (dateRange && dateRange !== 'ALL_TIME') {
      const gteDate = new Date();
      if (dateRange === 'TODAY') {
        gteDate.setHours(0, 0, 0, 0);
      } else if (dateRange === 'LAST_7_DAYS') {
        gteDate.setDate(gteDate.getDate() - 7);
      } else if (dateRange === 'LAST_30_DAYS') {
        gteDate.setDate(gteDate.getDate() - 30);
      } else if (dateRange === 'LAST_90_DAYS') {
        gteDate.setDate(gteDate.getDate() - 90);
      }
      matchStage['orderInfo.orderDate'] = { $gte: gteDate };
    }

    // 3. Early return for Tables
    if (widget.type === 'table') {
      const data = await Order.find(matchStage).sort({ 'orderInfo.orderDate': -1 }).limit(10);
      return res.json({ rows: data });
    }

    // 4. Construct Aggregation Pipeline dynamically
    const config = widget.config || {};
    const { xAxisField = 'product', yAxisField = 'totalAmount', aggregation = 'sum' } = config;
    
    // KPI Types
    if (widget.type === 'kpi') {
      const pipeline = [
        { $match: matchStage },
        { 
          $group: {
            _id: null,
            value: aggregation === 'sum' ? { $sum: `$orderInfo.${yAxisField}` } :
                   aggregation === 'average' ? { $avg: `$orderInfo.${yAxisField}` } :
                   aggregation === 'count' ? { $sum: 1 } : { $first: 0 }
          }
        }
      ];
      const result = await Order.aggregate(pipeline);
      return res.json({ value: result[0]?.value || 0 });
    }

    // Charts Types (Bar, Pie, Line)
    if (['bar', 'pie', 'line'].includes(widget.type)) {
      
      // Determine field format properly (nested 'customer.city' vs 'orderInfo.product')
      let mappedXField = xAxisField;
      if (['product', 'status', 'orderDate'].includes(xAxisField)) {
        mappedXField = `orderInfo.${xAxisField}`;
      } else if (xAxisField && !xAxisField.includes('.')) {
         mappedXField = `orderInfo.${xAxisField}`; // Fallback logic
      }

      let _idRef = `$${mappedXField}`;
      
      // Handle Date formatting for Line Charts based on OrderDate
      if (xAxisField === 'orderDate' || xAxisField === 'orderInfo.orderDate') {
        _idRef = { $dateToString: { format: "%Y-%m-%d", date: `$orderInfo.orderDate` } };
      }

      const pipeline = [
        { $match: matchStage },
        {
          $group: {
            _id: _idRef,
            yValue: aggregation === 'sum' ? { $sum: `$orderInfo.${yAxisField}` } :
                    aggregation === 'average' ? { $avg: `$orderInfo.${yAxisField}` } :
                    aggregation === 'count' ? { $sum: 1 } : { $first: 0 }
          }
        },
        { $sort: { _id: 1 } } // Sort by X-axis ascending (crucial for time series)
      ];

      const result = await Order.aggregate(pipeline);
      
      // Format payload for recharts: [ { name: xAxis, value: yAxis } ]
      const formattedSeries = result.map(bucket => ({
        [xAxisField]: bucket._id || 'Unknown',
        [yAxisField]: bucket.yValue
      }));

      return res.json({ series: formattedSeries });
    }

    // Default Fallback
    res.json({ message: 'Unsupported widget type' });

  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Error fetching analytics data', error: error.message });
  }
};
