const mongoose = require('mongoose');

const dashboardSchema = new mongoose.Schema({
  name: { type: String, required: true, default: 'My Dashboard' },
  isAutoGenerated: { type: Boolean, default: false },
  layouts: {
    lg: { type: Array, default: [] }, // Desktop (12 cols)
    md: { type: Array, default: [] }, // Tablet (8 cols)
    sm: { type: Array, default: [] }, // Mobile (4 cols)
    xs: { type: Array, default: [] },
    xxs: { type: Array, default: [] }
  },
  widgets: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Widget' }],
}, { timestamps: true });

module.exports = mongoose.model('Dashboard', dashboardSchema);
