const express = require('express');
const router = express.Router();
const {
  autoGenerateDashboard,
  aiGenerateDashboard,
  aiAnalyzeRequirement,
  getWidgetData
} = require('../controllers/analyticsController');

const { protect } = require('../middlewares/authMiddleware');

router.use(protect);

router.post('/auto-generate', autoGenerateDashboard);
router.post('/ai-generate', aiGenerateDashboard);
router.post('/ai-analyze', aiAnalyzeRequirement);
router.post('/data', getWidgetData);

module.exports = router;
